version: "3"
services:
  app:
    container_name: shopping-api
    depends_on:
      - shopping-mongo
    restart: unless-stopped
    build: ./
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    links:
      - shopping-mongo
  shopping-mongo:
    container_name: shopping-mongo
    image: mongo:5.0.6
    restart: unless-stopped
    ports:
      - "${MONGO_EXPOSE_PORT}:${MONGO_PORT}"